apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DATABASE_USERNAME: cG9zdGdyZXM=   # base64 encoded "postgres"
  DATABASE_PASSWORD: cG9zdGdyZXM=   # base64 encoded "postgres"
